### ISSUE TITLE
iOS Facebook sharing using Open Graph Share Dialog fails - error Code 102

### ISSUE THREAD

**Issue by vividcode** [fbsamples/ios-howtos#7]
I was following FBOGSampleSD for sharing with my open graph objects. 
Initially the code worked fine with stored login in my native iOS FB app but the moment I switched login it stopped working.
The error I get is this:

`(com.facebook.Facebook.platform error 102.)" UserInfo=0x20141c70 {error_code=102, error_description=An error occurred during publishing., app_id=244500685679948, error_reason=The operation couldn’t be completed. (FBAPIErrorDomain error 3506.)}`

Have posted it here too: 
http://stackoverflow.com/questions/27324966/ios-facebook-posting-using-open-graph-fails-error-code-102

Please help...

**Comment by caabernathy** [comment]
Check this link which I believe outlines the process https://developers.facebook.com/docs/opengraph/submission-process

In the meantime you can add the user as a tester for your app.
